version: '3.3'
services:
  keepalived:
    privileged: true
    restart: always
    network_mode: "host"
    image: 'lukics/keepalived:armv7'
    container_name: keepalived-${HOSTNAME}
    labels:
      - io.rancher.scheduler.global=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /root/.docker:/root/.docker    
    environment:
      - VIRTUAL_IP=192.168.3.200
      - VIRTUAL_ROUTER_ID='51'
      - INTERFACE='eth0'
      - PASSWORD=topsecret
      - PRIORITY='100'
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
